language: java
sudo: false # faster builds

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"
install: "/bin/true"

script:
  - mvn clean package
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
    name: $TRAVIS_TAG
    overwrite: true
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - target/*.jar
    on:
      branch: master
      repo: oprekable/java-command-pattern-example
      tags: true
      condition: $TRAVIS_TAG =~ ^release-[0-9]+\.[0-9]+\.[0-9]+