language: java
sudo: false

jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
install: "/bin/true"
jobs:
  include:
    - stage: Unit Tests
      script:
        - mvn clean package
        - mvn cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: GitHub Release
      if: branch = master AND tag =~ ^release-[0-9]+\.[0-9]+\.[0-9]+
        script:
          - echo "Build ..."
          - mvn clean package -DskipTests=true
          - echo "Deploying to GitHub releases ..."
        before_deploy:
          - export TRAVIS_TAG="$(echo "${TRAVIS_TAG}" | awk -F'-' '{print $2}')${$TRAVIS_BUILD_NUMBER}"
          - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
          - git config --local user.name "$USER_NAME"
          - git config --local user.email "$USER_EMAIL"
          - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
        deploy:
          - provider: releases
            tag_name: $TRAVIS_TAG
            target_commitish: $TRAVIS_COMMIT
            name: $TRAVIS_TAG
            overwrite: true
            skip_cleanup: true
            api_key: $GITHUB_TOKEN
            file_glob: true
            file:
              - target/*.jar
            on:
              branch: master
              repo: oprekable/java-command-pattern-example