language: java
sudo: false # faster builds
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2/repository"
install: "/bin/true"

script:
  - mvn clean package -DbuildNumber=$TRAVIS_BUILD_NUMBER
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - target/*.jar
  on:
    branch: master
    repo: oprekable/java-command-pattern-example

notifications:
  email:
    on_success: never
    on_failure: always